---

- name: Test distribution
  assert:
    that: >
      ansible_facts.os_family == 'RedHat' or
      ansible_facts.os_family == 'Debian'

- name: Add SCL YUM repo
  yum_repository:
    name: scl
    description: SCL YUM repo
    baseurl: "{{ haproxy_scl_yum_repo_url }}"
    gpgcheck: no
  args: "{{ haproxy_scl_yum_repo_params }}"
  when: >
    ansible_facts.os_family == 'RedHat' and
    ansible_facts.distribution_major_version | int > 6 and
    haproxy_scl_yum_repo_install == true
  tags:
    - haproxy_pkg

- name: Add APT repo
  apt_repository:
    repo: "{{ haproxy_apt_repo_string }}"
  args: "{{ haproxy_apt_repo_params }}"
  when: >
    ansible_facts.os_family == 'Debian' and
    haproxy_apt_repo_install == true
  tags:
    - haproxy_pkg

- name: Install HAproxy package
  package:
    name: "{{ haproxy_pkg }}"
  notify:
    - Restart HAproxy service
  tags:
    - haproxy_pkg

- name: Configure HAproxy Sysconfig
  template:
    src: sysconfig.j2
    dest: "{{ haproxy_sysconfig_path }}"
  when: >
    ansible_facts.os_family == 'RedHat'
  notify: Restart HAproxy service
  tags:
    - haproxy_config

- name: Configure HAproxy default file
  template:
    src: default.j2
    dest: "{{ haproxy_default_path }}"
  when: >
    ansible_facts.os_family == 'Debian'
  notify: Restart HAproxy service
  tags:
    - haproxy_config

- name: Configure HAproxy
  template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_config_path }}"
  notify: Reload HAproxy service
  tags:
    - haproxy_config

- name: Enable HAproxy service
  service:
    name: "{{ haproxy_service }}"
    enabled: yes
  tags:
    - haproxy_service

- name: Start HAproxy service
  service:
    name: "{{ haproxy_service }}"
    state: started
  register: haproxy_service_started
  tags:
    - haproxy_service
